---
# This master playbook deploys the ECGPS application to a single server.
- hosts: all
  tasks:
    - name: group dev_hosts by distribution
      group_by: key="{{ ansible_distribution }}-{{ ansible_distribution_version }}"

- hosts: Ubuntu-12*:Ubuntu-13*
  user: root
  roles:
    - { role: packages_ubuntu }
    - { role: common }
    - { role: postgres, pg_hba_location: "/etc/postgresql/9.1/main/pg_hba.conf" }
    - { role: btsync }
    - { role: ecgps }
    - { role: nginx }

- hosts: RedHat-6*:CentOS-6*:SL-6*
  user: root
  roles:
    - { role: packages_el6 }
    - { role: common }
    - { role: postgres, pg_hba_location: "/var/lib/pgsql/data/pg_hba.conf" }
    - { role: btsync }
    - { role: ecgps }
    - { role: nginx }

- hosts: Fedora-*
  user: root
  roles:
    - { role: packages_fedora }
    - { role: common }
    - { role: postgres, pg_hba_location: "/var/lib/pgsql/data/pg_hba.conf" }
    - { role: btsync }
    - { role: ecgps }
    - { role: nginx }




