---
# Tasks for installing and configuring eClinicalgps.

- name: Pull the ecgps app from the github repo.
  git: repo=$project_repo dest=$project_root/ecgps version={{branch}}
  tags: deploy

- name: Upgrade the virtualenv with dev requirements.
  pip: requirements=${project_root}/ecgps/deps/development.txt virtualenv=${env_dir}
  only_if: "'$machine' == 'dev'"
  tags: deploy, dev

- name: Upgrade the virtualenv with production requirements.
  pip: requirements=${project_root}/ecgps/deps/production.txt virtualenv=${env_dir}
  tags: deploy

- name: Delete Root SSH Directory.
  file: state=directory path=~/.ssh state=absent
  tags: provision

- name: check if local_settings.py.j2 exists
  shell: "[ -f ${project_root}/ecgps/local_settings.py ] && echo True || echo False"
  register: no_local_settings
  tags: deploy, dev

- name: copy over local_settings if one is needed
  template: src=local_settings.py.j2 dest=${project_root}/ecgps/local_settings.py
  only_if: "${no_local_settings}"
  tags: deploy, dev

- name: Sync Django database.
  shell: ${env_dir}/bin/python $project_root/ecgps/manage.py syncdb --migrate --noinput
  tags: deploy

- name: Do Django collectstatic to grab media files .
  shell: ${env_dir}/bin/python $project_root/ecgps/manage.py collectstatic --noinput
  tags: deploy

- name: start redis-server
  action: service name=redis-server state=started enabled=yes
  tags: deploy, dev

#- name: Load fixtures
#  django_manage: >
#    command=loaddata
#    app_path=${project_root}/ecgps
#    fixtures=dev_fixtures/auth.json, dev_fixtures/bare_auth.json, dev_fixtures/bare_ecgps_core.json, dev_fixtures/bare_sites.json, dev_fixtures/ecgps_core.json, dev_fixtures/pm_core.json. dev_fixtures/sites.json
#  only_if: "'$machine' == 'dev'"
#  ignore_errors: True
#  tags: deploy, dev

- name: copy load fixtures script.
  template: src=load_fixtures.py.j2 dest=/tmp/load_fixtures.py
  only_if: "'$machine' == 'dev'"
  tags: deploy, dev

- name: Load fixtures.
  shell: /usr/bin/python /tmp/load_fixtures.py
  only_if: "'$machine' == 'dev'"
  ignore_errors: True
  tags: deploy, dev

- name: Change ownership of ecgps installation
  file: path=${project_root} owner=${user_name} group=${user_name} state=directory recurse=yes
  tags: deploy, dev

#- name: Run django runserver
#  shell: ${env_dir}/bin/python ${project_root}/ecgps/manage.py runserver {{inventory_hostname}}:8000
#  only_if: "'$machine' == 'dev'"
#  tags: deploy, dev

#- name: stop supervisor
#  service: name={{sup_init_name}} state=stopped
#  tags: depoly, supervisor

#- name: start supervisor
#  service: name={{sup_init_name}} state=started enabled=yes
#  tags: deploy, supervisor

